version: '3.8'

services:
  jmcomic-reader:
    image: bingking148/jmcomic-reader:latest
    container_name: jmcomic-reader
    ports:
      - "5000:5000"
    volumes:
      - ./data/DownloadedComics:/app/DownloadedComics
      - ./data/TempCache:/app/TempCache
      - ./data/backend:/app/backend
    environment:
      PYTHONUNBUFFERED: "1"
      FLASK_ENV: "production"
      BASE_DIR: "/app"
      DOWNLOAD_DIR: "/app/DownloadedComics"
      TEMP_CACHE_DIR: "/app/TempCache"
    restart: unless-stopped
