# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['desktop_app.py'],
    pathex=[],
    binaries=[],
    datas=[('frontend', 'frontend'), ('VERSION', '.')],
    hiddenimports=[
        'webview',
        'webview.platforms.edgechromium',
        'webview.platforms.winforms',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'av',
        'cv2',
        'fastapi',
        'gradio',
        'librosa',
        'llvmlite',
        'matplotlib',
        'numba',
        'openpyxl',
        'paddle',
        'pandas',
        'scipy',
        'sklearn',
        'soundfile',
        'sqlalchemy',
        'sympy',
        'tensorboard',
        'tensorflow',
        'torch',
        'torchaudio',
        'torchvision',
        'transformers',
        'triton',
        'uvicorn',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='JMComicReader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon='assets\\app_icon.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='JMComicReader',
)
